### ISSUE TITLE
Boss Attack Effect

### ISSUE THREAD

**Issue by jiye-stingray** [Train-Adventure-Endless-Challenge/Train-Adventure#163]
바닥에나오는 이펙트가 중앙에 있어요. 좀 크고 팔쪽에 나왔으면좋겠어요

_Originally posted by @JungEunseong in https://github.com/Train-Adventure-Endless-Challenge/Train-Adventure/issues/162#issuecomment-1620309049_

**Comment by jiye-stingray** [comment]
펀치 공격 Effect를 말씀하시는 건가요 아니면 점프 공격 Effect를 말씀하시는건가요?

**Comment by JungEunseong** [comment]
> 펀치 공격 Effect를 말씀하시는 건가요 아니면 점프 공격 Effect를 말씀하시는건가요?

아! 점프공격이요

**Comment by jiye-stingray** [comment]
제 생각에는 발 쪽이랑 같이 착지 되어서 Effect 크기만 좀 크게 수정하면 될 것 같은데 어떻게 생각하세요?

**Comment by jiye-stingray** [comment]
https://github.com/Train-Adventure-Endless-Challenge/Train-Adventure/assets/81548078/6fa9da37-7dc0-4e41-a83e-5a8cc3ea95ce

@JungEunseong 어떠신가요?
