### ISSUE TITLE
플레이어 Hit시 애니메이션 버그

### ISSUE THREAD

**Issue by qkrwoaks** [Train-Adventure-Endless-Challenge/Train-Adventure#267]
플레이어가 몬스터에 Hit 당했는데 애니메이션이 2번 이상 실행되는 버그

**Comment by jiye-stingray** [comment]
제가 생각하기엔 플레이어가 HIt 상태 일 시 피격을 받으면 다음에 Hit 애니메이션이 또 호출된다고 생각합니다

**Comment by qkrwoaks** [comment]
애니메이션 구조에서 한 상태가 2번 이상 실행되는 일을 피하고자 Trigger 상태로 OnState라는 애니메이터 변수를 만들어 두었습니다.
하지만 몬스터에게 한번 공격받을 시 두 번 이상 실행되어 애니메이션이 중복으로 반복되는 일이 빈번치 않게 일어납니다.
어떠한 이유로 그런 식으로 되었는지는 아직 잘 모르겠지만, 의도한 부분이 아니기에 고쳐야 할 부분이라고 생각합니다.
또한 플레이어가 HIt 상태 일 시 피격을 받으면 다음에 Hit 애니메이션이 또 호출되는 것은 의도한 부분입니다.

* 버그 영상

https://github.com/Train-Adventure-Endless-Challenge/Train-Adventure/assets/82390527/71b3fbc7-475e-42bb-a013-8cecf535f8c6

**Comment by jiye-stingray** [comment]
아하! 그럼 Hit 함수 자체가 피격 시 2번 호출되는 건 아닐까요? 단순히 애니메이션만 2번 호출되는 건가요 ?

**Comment by qkrwoaks** [comment]
확인 해 본 결과 단순히 애니메이션만 2번 호출되는 것 같습니다.
UI 작업이 끝난 후 해결 해보도록 하겠습니다.
